apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service-fixed
  namespace: ecommerce
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-ip: "172.18.0.5"
spec:
  selector:
    app: ecommerce-simple
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
