apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-simple
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-simple
  template:
    metadata:
      labels:
        app: ecommerce-simple
    spec:
      containers:
      - name: ecommerce-simple-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
